version: '3.8'

services:
  food-be:
    image: 'tuannm99/food-be'
    ports: 
      - 5000:5000
    depends_on:
      - mongo
    environment:
      NODE_ENV: 'development'
      MONGO_URL: 'mongodb://minhtuan:12345678@mongo:27017'
      MONGO_DB_NAME: 'food'
    networks:
      - food

  food-fe:
    image: 'tuannm99/food-fe'
    ports: 
      - 80:80
    networks:
      - food

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: minhtuan
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    volumes:
      - '~/Development/docker/data/mongo:/data/db'
    networks:
      - food

networks:
  food:
    driver: bridge

